### ISSUE TITLE
Reply from I2C-slave is always zero!

### ISSUE THREAD

**Issue by WernerBaeuerle** [thexeno/HardWire-Arduino-Library#12]
For my current Arduino project I activated the I2C interface in slave mode. My first trials with the original wire.h library failed because the I2C master in my environment didn't support clock stretching. Therefore I changed the library into HardWire.h (version 1.0.3), but this generates other problems: The reply from the slave towards the master is always zero. This was verified with the help of an oscilloscope and I2C analyzer also.

Attached you can find my simple code:

==================================================================================

// I2C Interface (Slave) to control an external device (automotive)
//
// Arduino-Board:  Pro Mini(5.0V/16MHz) ATmega328
// Compiler-Tool:  Arduino IDE 1.8.9

#include <HardWire.h>

// Define the usage of the Arduino pins
int  accctrl_pin =  5;   // ACC control        (low = off, high = power)
int boardled_pin = 13;   // Arduino board LED  (low = off, high = on   )

#define SLAVE_ADDR 0x63
byte command[4] = {0x00, 0x00, 0x00, 0x00}; // command buffer
int j = 0;

void setup(){
    // Define the direction of the Arduino pins
    pinMode( accctrl_pin, OUTPUT);
    pinMode(boardled_pin, OUTPUT);
    
    // Join the I2C-Bus as a slave device (HW I2C port, used pins: A4/A5)
    Wire.begin(SLAVE_ADDR, HARD_WIRE_MODE);
    // Function to run when data received from master
    Wire.onReceive(receiveEvent);
    // Function to run when data requested from master
    Wire.onRequestData(requestEvent);

    // Switch on the external device after Power-up or Reset and flash board-LED
    digitalWrite(accctrl_pin, HIGH);
    digitalWrite(boardled_pin, HIGH);
    delay(100);
    digitalWrite(boardled_pin, LOW);
}

void loop() {
  delay(100);  
}

// I2C Master writes data (interrupt service routine)
void receiveEvent() {
    // Fill command buffer
    while (0 < Wire.available()) {
    command[j] = Wire.read();
    j++;
    }
    j = 0;
    //digitalWrite(boardled_pin, HIGH); // for Debug only!
}

// I2C Master reads data (interrupt service routine)
byte requestEvent() {
   // Reply towards master
   byte value = 0x6B;
   digitalWrite(boardled_pin, HIGH); // for Debug only!
return value;
}

==================================================================================

I inserted debug instructions (switch on board LED) in the handler and found out that it worked fine in the "void receiveEvent()"-handler but failed in the "byte requestEvent()"-handler.

After replacing Wire.onRequestData(requestEvent) by Wire.onRequest(requestEvent) there are no problems!

Conclusion: the Wire.onRequestData(requestEvent) function will be never executed (because of missing interrupt)!

I'm familiar with the I2C interface but my skill is more hardware oriented. Maybe my code is wrong or I understood the mechanism of the functions completely wrong?

Remark: the examples, included in the hardwire library, are not useful for me!

**Comment by thexeno** [comment]
Hi, many thanks for reporting this. I will try to reproduce it!

**Comment by thexeno** [comment]
Hi,

can you try the branch from the repository in my profile? Is called "new_fix_slave_tx".

If you use a buffer in HARD_WIRE_MODE, it will be circular (i.e. never finish to answer to the master and swipes the same internal buffer).
You can use the Wire.read()/write() (which use the internal buffer used by the official Arduino lib) as long as you don't use the slave transmit callbacks.
This means that defining onRequestData(uint8_t (*function)(void)), while in SLAVE mode, you can still with Wire.read() receive what the MASTER send. But you can ONLY send back data TO master by using the return values from onRequestData and you CANNOT use the internal buffer to send data back to master, meaning you won't send data using the Wire.write() while in slave transmit mode.

If you need a buffer and an index, you can implement it in your application and interface with the HardWire lib via return values from your buffer sent via onRequestData. This library was developed to allow the Arduino to emulate I2C slaves which performs different actions between various I2C bus states, and knowing this difference, you should be able to use the library without catches.
If you don't define onRequestData callback, there should be no issues in using the Wire.read()/write(), and is backward compatible with Wire.

I will update the documentation and make an example or two. First let me know if this works accordingly, maybe by sending back a snippet of the code, like you did before. 

Thank you

**Comment by WernerBaeuerle** [comment]
Hello thexeno,

I checked your modified library and confirm that the problem is solved. You can close the issue!

The verification was done in my testbench with the following source code:

==============================================================
// I2C Interface (Slave)
//
// Arduino-Board:  Pro Mini(5.0V/16MHz) ATmega328
// Compiler-Tool:  Arduino IDE 1.8.9

#include <HardWire.h>

// Define the usage of the Arduino pins
int  accctrl_pin =  5;   // ACC control        (low = off, high = power)
int boardled_pin = 13;   // Arduino board LED  (low = off, high = on   )

#define SLAVE_ADDR 0x63
byte command[4] = {0x00, 0x00, 0x00, 0x00}; // command buffer
int j = 0;
byte reply[2] = {0x2B, 0x6B}; // possible replies
int k = 1;

void setup(){
    // Define the direction of the Arduino pins
    pinMode( accctrl_pin, OUTPUT);
    pinMode(boardled_pin, OUTPUT);
    
    // Join the I2C-Bus as a slave device (HW I2C port, used pins: A4/A5)
    Wire.begin(SLAVE_ADDR, HARD_WIRE_MODE);
    // Function to run when data received from master
    Wire.onReceive(receiveEvent);
    // Function to run when data requested from master
    Wire.onRequestData(requestEvent);

    // Switch on the external device after Power-up or Reset and flash board-LED
    digitalWrite(accctrl_pin, HIGH);
    digitalWrite(boardled_pin, HIGH);
    delay(100);
    digitalWrite(boardled_pin, LOW);
}


void loop() {
  
  delay(100);
  
}

// I2C Master writes data (interrupt service routine)
void receiveEvent() {

    // Fill command buffer
    while (0 < Wire.available()) {
    command[j] = Wire.read();
    j++;
    }
    j = 0;
  //digitalWrite(boardled_pin, HIGH); // for Debug only!

}


// I2C Master reads data (interrupt service routine)
byte requestEvent() {
  
    // Toggle Reply towards master
    if (k == 0) {
       k++;
    } else {
       k--;
    }
  //digitalWrite(boardled_pin, HIGH); // for Debug only!

return reply[k];

}
==============================================================

Now the data, sent to the I2C-master, toggles between 0x2B and 0x6B as expected. Before the correction it was 0x00 always.

Thank you very much

Werner
