### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by kb-** [thexeno/HardWire-Arduino-Library#3]
Hi, I'm getting compilation errors when I try using HardWire with the Arduino Wire tutorial scripts. I attached the log files.
[Mega2560 compilation error.txt](https://github.com/thexeno/HardWire-Arduino-Library/files/692346/Mega2560.compilation.error.txt)
[Nano Zero compilation error.txt](https://github.com/thexeno/HardWire-Arduino-Library/files/692347/Nano.Zero.compilation.error.txt)

**Comment by thexeno** [comment]
Hi,
for the Mega, seems just a lack on finding the correct declarations.

For the Zero, there are probably different registers used in the MCU hardware, so over the previous declaration errors, you will have compatibility issues. It has a completely different MCU architecture, the TWI library already available may be very different from the Atmega series MCUs. (EDIT: I confirm, the I2C module is handled very differently)

Can you attach the entire project for the Mega at least?

**Comment by kb-** [comment]
I only tried the short example from the Wire library. I know the Zero is handled differently. I hoped finding a library behaving more consistently than Wire. For example, the Zero sometimes doesn't like communicating in master mode if the optional address is set.

[HardWire_master_reader.zip](https://github.com/thexeno/HardWire-Arduino-Library/files/706830/HardWire_master_reader.zip)

**Comment by thexeno** [comment]
Hi,

try with the latest commit. It is not fixed for the Zero, but now should work for all the previously supported by the classic Wire.

Let me know ;)

**Comment by kb-** [comment]
Hi, it's working for the Mega. Sorry for the late response.

It's still not compiling for the Zero. The error messages are different from last time.
[error.txt](https://github.com/thexeno/HardWire-Arduino-Library/files/819894/error.txt)
