### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by maxholgasson** [thexeno/HardWire-Arduino-Library#4]
Hi, 
the original twi.c has the lack of a timeout. My I2C connection breaks from time to time and the arduino freezes and is totally blocked till i reset it by hand.
Here is a solution so far obviously
https://github.com/MauroMombelli/Arduino/blob/7c87e9b933cd80927e684920a7e8801a7ae89e3f/libraries/Wire/utility/twi.c

Is this considered in your library?

**Comment by thexeno** [comment]
Hi, it is not yet considered since this was just a simple porting from the original one. I may include the one linked on my own too, or finding something else. 
Actually I already developed a full I2C library for the Atmegas, completely non blocking, but it is not Arduino/Wire compatible.
