### ISSUE TITLE
Trying to get in touch with the author.

### ISSUE THREAD

**Issue by AndKe** [thexeno/HardWire-Arduino-Library#9]
Checking if you could please help me determine whatever this library will save my day (having some issues with flexibility of the Arduino library)

**Comment by thexeno** [comment]
Hi, yes I can try. Tell me the issue you have

**Comment by thexeno** [comment]
> 
> 
> Checking if you could please help me determine whatever this library will save my day (having some issues with flexibility of the Arduino library)

Hi, can I close the issue by now? I am going to make a small revision hence I am trying to close different issues.

**Comment by AndKe** [comment]
Yes, sorry, I figured things out.
